=== screap/MyTestRepo/stripes/content/content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="all">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="color"/>
							<xs:element name="size"/>
							<xs:element name="id" minOccurs="0"/>
							<xs:element name="title" minOccurs="0"/>
							<xs:element name="description" minOccurs="0"/>
							<xs:element name="content" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:sequence minOccurs="0">
										<xs:element name="image" minOccurs="0"/>
										<xs:element name="include" minOccurs="0"/>
										<xs:element name="link" minOccurs="0">
											<xs:complexType mixed="true">
												<xs:sequence>
													<xs:element name="description" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== screap/MyTestRepo/stripes/content/content.xml
<?xml version='1.0' encoding='UTF-8'?>
<all xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="content.xsd">
	<item>
		<color>#774638</color>
		<size>50</size>
	</item>
	<item>
		<color>#ec6700</color>
		<size>110</size>
	</item>
	<item>
		<color>#f83885</color>
		<size>50</size>
	</item>
	<item>
		<color>#ec6700</color>
		<size>70</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
	<item>
		<color>#f83885</color>
		<size>150</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>40</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>200</size>
		<id>home</id>
		<title>Home</title>
		<description>Startseite</description>
		<content>
			[i]"Feel free to zoom (Strg + Mausrad)."[/i]
		</content>
	</item>
	<item>
		<color>#f41528</color>
		<size>50</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>70</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>40</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>30</size>
	</item>
	<item>
		<color>#774638</color>
		<size>170</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
	<item>
		<color>#f9ad00</color>
		<size>70</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>50</size>
	</item>
	<item>
		<color>#f9ad00</color>
		<size>100</size>
		<id>graph</id>
		<title>Graph</title>
		<description>Diagramm</description>
		<content>
			<include>graph.php</include>
		</content>
	</item>
	<item>
		<color>#c44079</color>
		<size>40</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>50</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>50</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>100</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>40</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>70</size>
	</item>
	<item>
		<color>#f83885</color>
		<size>50</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>100</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>120</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
	<item>
		<color>#774638</color>
		<size>150</size>
	</item>
	<item>
		<color>#ec6700</color>
		<size>30</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
	<item>
		<color>#f41528</color>
		<size>150</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>50</size>
	</item>
	<item>
		<color>#ec6700</color>
		<size>50</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>70</size>
	</item>
	<item>
		<color>#f83885</color>
		<size>30</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>50</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>110</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>70</size>
	</item>
	<item>
		<color>#f9ad00</color>
		<size>100</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
	<item>
		<color>#c44079</color>
		<size>70</size>
	</item>
	<item>
		<color>#ec6700</color>
		<size>30</size>
	</item>
	<item>
		<color>#c44079</color>
		<size>50</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>50</size>
	</item>
	<item>
		<color>#c44079</color>
		<size>50</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>120</size>
	</item>
	<item>
		<color>#774638</color>
		<size>30</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>40</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>40</size>
	</item>
	<item>
		<color>#aecf02</color>
		<size>150</size>
		<id>kontakt</id>
		<title>Kontakt</title>
		<description>Kontaktformular</description>
		<content>
			[i]"Was willst du von mir?"[/i]
			<include>contact.php</include>
		</content>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>40</size>
	</item>
	<item>
		<color>#f41528</color>
		<size>40</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>40</size>
	</item>
	<item>
		<color>#f41528</color>
		<size>70</size>
		<id>impressum</id>
		<title>Impressum</title>
		<description>Impressum</description>
		<content>
			[i]"Wofür übernehm&apos; ich eigentlich keine Haftung?"[/i]
			<link>mailto:smile@screap.de
				<description>smile@screap.de</description>
			</link>
		</content>
	</item>
	<item>
		<color>#f83885</color>
		<size>70</size>
	</item>
	<item>
		<color>#f41528</color>
		<size>50</size>
	</item>
	<item>
		<color>#00bdbb</color>
		<size>40</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>30</size>
	</item>
	<item>
		<color>#a1954b</color>
		<size>40</size>
	</item>
	<item>
		<color>#eef2f3</color>
		<size>50</size>
	</item>
</all>
